name: PayPay Java SDK CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up openjdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run coverage
        run: |
          ./gradlew clean build jacocoTestReport

      - name: Upload to CoPilot
        run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)

      - name: Upload coverage GitHub artifact
        uses: actions/upload-artifact@v2
        with:
          # Consumed by the `build-ci-target.yml` `upload-codeclimate` job.
          name: jacoco-coverage
          path: ./build/reports/jacoco/test/jacocoTestReport.xml
